version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: baseejemplo
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-net

  product-service:
    build: ./product
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/baseejemplo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      INVENTORY_SERVICE_URL: http://inventory-service:8081
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - microservices-net

volumes:
  mysql_data:

networks:
  microservices-net:
    driver: bridge
